import type { Contact } from "./whatsapp-app.types"

export const contacts: Contact[] = [
  {
    id: "stalker",
    name: "Stalker",
    initial: "S",
    gradient: "linear-gradient(135deg, #434343 0%, #000000 100%)",
    lastTime: "11:02 AM",
    unread: 5,
    unreadFrom: 3,
    previewIndex: 6,
    messages: [
      { text: "hey", time: "10:51 AM", isOut: false },
      { text: "nice portfolio btw", time: "10:52 AM", isOut: false },
      { text: "i see you're online a lot late at night 👀", time: "10:54 AM", isOut: false },
      { text: "do you always code at 2am?", time: "10:57 AM", isOut: false },
      { text: "just noticed you updated your github profile pic", time: "10:59 AM", isOut: false },
      { text: "you wear the same blue hoodie in like all your photos lol", time: "11:01 AM", isOut: false },
      { text: "anyway just wanted to say hi", time: "11:02 AM", isOut: false },
      { text: "hello???", time: "11:03 AM", isOut: false },
    ],
  },
  {
    id: "recruiter",
    name: "Recruiter",
    initial: "R",
    gradient: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    lastTime: "10:48 AM",
    messages: [
      { text: "Hi Nihir, I came across your portfolio. Your work on the OmniSearch Engine is impressive!", time: "10:30 AM", isOut: false },
      { text: "Hi! Thanks for reaching out. I really enjoyed building that project, especially the ML-powered relevance ranking.", time: "10:35 AM", isOut: true },
      { text: "We're looking for a Full Stack Engineer at our company. Are you currently open to new opportunities?", time: "10:38 AM", isOut: false },
      { text: "Yes, I am! I'm looking for roles where I can build scalable systems and great user experiences.", time: "10:42 AM", isOut: true },
      { text: "Perfect. When would be a good time to hop on a quick call this week?", time: "10:45 AM", isOut: false },
      { text: "I'm available on Thursday afternoon. Feel free to check my Calendar app to book a slot!", time: "10:48 AM", isOut: true },
    ],
  },
  {
    id: "admirer",
    name: "Admirer",
    initial: "A",
    gradient: "linear-gradient(135deg, #f7971e 0%, #ffd200 100%)",
    lastTime: "9:44 AM",
    messages: [
      { text: "bro just saw your portfolio... this is actually insane 😭", time: "9:30 AM", isOut: false },
      { text: "haha thanks man, took forever to build", time: "9:32 AM", isOut: true },
      { text: "the whatsapp app INSIDE the phone?? that's so meta lmaooo", time: "9:35 AM", isOut: false },
      { text: "lol yeah, recursive portfolio achieved 😂", time: "9:37 AM", isOut: true },
      { text: "you're gonna get hired in like 5 minutes fr fr", time: "9:40 AM", isOut: false },
      { text: "from your mouth to god's ears 🙏", time: "9:44 AM", isOut: true },
    ],
  },
  {
    id: "bestie",
    name: "Bestie",
    initial: "B",
    gradient: "linear-gradient(135deg, #ee0979 0%, #ff6a00 100%)",
    lastTime: "Yesterday",
    messages: [
      { text: "BRO", time: "8:15 PM", isOut: false },
      { text: "your portfolio is actually insane wtf 💀", time: "8:15 PM", isOut: false },
      { text: "lmaooo you finally checked it", time: "8:17 PM", isOut: true },
      { text: "the whatsapp thing is SENDING me bro 💀💀💀", time: "8:18 PM", isOut: false },
      { text: "3 weeks of my life went into that lol", time: "8:20 PM", isOut: true },
      { text: "worth it bhai, you're definitely cooked... in a good way", time: "8:21 PM", isOut: false },
      { text: "when's the Netflix subscription though 😂", time: "8:22 PM", isOut: false },
      { text: "bro the Netflix in there actually works kinda 💀", time: "8:24 PM", isOut: true },
    ],
  },
  {
    id: "mom",
    name: "Mom",
    initial: "M",
    gradient: "linear-gradient(135deg, #f953c6 0%, #b91d73 100%)",
    lastTime: "Yesterday",
    unread: 2,
    unreadFrom: 6,
    messages: [
      { text: "beta what is this website you sent me", time: "2:10 PM", isOut: false },
      { text: "Ma it's my portfolio, for job applications 😅", time: "2:13 PM", isOut: true },
      { text: "it's very nice beta 😊 aapne bahut mehnat ki", time: "2:15 PM", isOut: false },
      { text: "thanks Ma 🙏", time: "2:16 PM", isOut: true },
      { text: "but beta when will you get a proper job. Your cousin Rahul got placed at TCS", time: "2:18 PM", isOut: false },
      { text: "Ma I know... I'm working on it 😭", time: "2:20 PM", isOut: true },
      { text: "ok ok. kal ghar aayega? Main teri favourite dish banaungi 🫶", time: "2:22 PM", isOut: false },
      { text: "miss you beta", time: "2:23 PM", isOut: false },
    ],
  },
  {
    id: "midnight",
    name: "Midnight Dev",
    initial: "D",
    gradient: "linear-gradient(135deg, #0f0c29 0%, #302b63 50%, #24243e 100%)",
    lastTime: "Mon",
    unread: 1,
    unreadFrom: 7,
    messages: [
      { text: "yo are you up", time: "2:47 AM", isOut: false },
      { text: "yeah what's up", time: "2:48 AM", isOut: true },
      { text: "just noticed your OmniSearch uses Redis for caching", time: "2:49 AM", isOut: false },
      { text: "yeah, why?", time: "2:50 AM", isOut: true },
      { text: "have you tried Dragonfly DB? supposedly 25x faster than Redis", time: "2:51 AM", isOut: false },
      { text: "bro it's 3am and you're benchmarking databases 💀", time: "2:52 AM", isOut: true },
      { text: "it's 2:52 not 3am", time: "2:52 AM", isOut: false },
      { text: "same thing bro go to sleep", time: "2:53 AM", isOut: true },
      { text: "ok but seriously try it. also found a potential memory leak in your indexer 👀", time: "2:54 AM", isOut: false },
    ],
  },
  {
    id: "wrongnumber",
    name: "+91 98765 43210",
    initial: "?",
    gradient: "linear-gradient(135deg, #606c88 0%, #3f4c6b 100%)",
    lastTime: "Sun",
    messages: [
      { text: "hey is this Priya's number?", time: "6:12 PM", isOut: false },
      { text: "wrong number, this is Nihir", time: "6:14 PM", isOut: true },
      { text: "oh sorry!! wait... are you the person who made that phone portfolio thing?", time: "6:15 PM", isOut: false },
      { text: "haha yeah that's me", time: "6:16 PM", isOut: true },
      { text: "my friend sent me the link earlier, it's actually so cool omg", time: "6:17 PM", isOut: false },
      { text: "thanks, glad you liked it!", time: "6:18 PM", isOut: true },
      { text: "anyway sorry for the wrong text 😅 but fr great work. good luck!", time: "6:19 PM", isOut: false },
      { text: "haha thanks, good luck finding Priya 😂", time: "6:21 PM", isOut: true },
    ],
  },
]
